name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Change this to your default branch if necessary

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: |
          chmod +x ./docker/build-docker-image.sh  # Make the script executable
          ./docker/build-docker-image.sh  # Run the script
